#symfonycasts_reset_password:
#    request_password_repository: App\Repository\ResetPasswordRequestRepository
# config/packages/reset_password.yaml
symfonycasts_reset_password:
    request_password_repository: App\Repository\ResetPasswordRequestRepository
    # Tiempo que el enlace es válido (en segundos). Ejemplo: 1 hora.
    lifetime: 3600
    # Tiempo (en segundos) que debe pasar entre peticiones.
    # Ponlo a 0 para que te deje enviar correos seguidos mientras pruebas.
    throttle_limit: 0
