services:
    # Servicio de Base de Datos
    db:
        image: mysql:8.0
        container_name: symfony_db
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: admin
            MYSQL_DATABASE: edukey_db
            MYSQL_USER: edukey_user
            MYSQL_PASSWORD: edukey_password
        volumes:
            - db_data:/var/lib/mysql
            # Mapeamos nuestro script dentro de la carpeta de inicialización de MySQL
            - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
        ports:
            - "3326:3306"
        networks:
            - edukey_network

    # Servicio Web (Apache + PHP)
    web:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        container_name: symfony_web
        restart: always
        ports:
            - "8082:80"
        depends_on:
            - db
        networks:
          - edukey_network
networks:
  edukey_network:
    driver: bridge

volumes:
    db_data:
