
services:
###> doctrine/doctrine-bundle ###
  database:
    image: mysql:8.0
    container_name: symfony_db
    environment:
      MYSQL_DATABASE: edukey_db
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: edukey_user
      MYSQL_PASSWORD: edukey_password
    ports:
      - "3316:3306"
    volumes:
      - database_data:/var/lib/mysql:rw
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
